version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://furniture-backend-ikq3.onrender.com
    restart: unless-stopped
    networks:
      - furniture-network

networks:
  furniture-network:
    external: true
